bedroom_choices = {
  '1':1,
  '2':2,
  '3':3,
  '4':4,
  '5':5,
  '6':6,
  '7':7,
  '8':8,
  '9':9,
  '10':10
  }

price_choices = {
  '100000':'Rs 100,0000',
  '200000':'Rs 200,0000',
  '300000':'Rs 300,0000',
  '400000':'Rs 400,0000',
  '500000':'Rs 500,0000',
  '600000':'Rs 600,0000',
  '700000':'Rs 700,0000',
  '800000':'Rs 800,0000',
  '900000':'Rs 900,0000',
  '1000000':'Rs 1 Cr+',
}

state_choices = {
  'BR': 'Bihar'
        
        # 'AK': 'Alaska',
        # 'AL': 'Alabama',
        # 'AR': 'Arkansas',
        # 'AS': 'American Samoa',
        # 'AZ': 'Arizona',
        # 'CA': 'California',
        # 'CO': 'Colorado',
        # 'CT': 'Connecticut',
        # 'DC': 'District of Columbia',
        # 'DE': 'Delaware',
        # 'FL': 'Florida',
        # 'GA': 'Georgia',
        # 'GU': 'Guam',
        # 'HI': 'Hawaii',
        # 'IA': 'Iowa',
        # 'ID': 'Idaho',
        # 'IL': 'Illinois',
        # 'IN': 'Indiana',
        # 'KS': 'Kansas',
        # 'KY': 'Kentucky',
        # 'LA': 'Louisiana',
        # 'MA': 'Massachusetts',
        # 'MD': 'Maryland',
        # 'ME': 'Maine',
        # 'MI': 'Michigan',
        # 'MN': 'Minnesota',
        # 'MO': 'Missouri',
        # 'MP': 'Northern Mariana Islands',
        # 'MS': 'Mississippi',
        # 'MT': 'Montana',
        # 'NA': 'National',
        # 'NC': 'North Carolina',
        # 'ND': 'North Dakota',
        # 'NE': 'Nebraska',
        # 'NH': 'New Hampshire',
        # 'NJ': 'New Jersey',
        # 'NM': 'New Mexico',
        # 'NV': 'Nevada',
        # 'NY': 'New York',
        # 'OH': 'Ohio',
        # 'OK': 'Oklahoma',
        # 'OR': 'Oregon',
        # 'PA': 'Pennsylvania',
        # 'PR': 'Puerto Rico',
        # 'RI': 'Rhode Island',
        # 'SC': 'South Carolina',
        # 'SD': 'South Dakota',
        # 'TN': 'Tennessee',
        # 'TX': 'Texas',
        # 'UT': 'Utah',
        # 'VA': 'Virginia',
        # 'VI': 'Virgin Islands',
        # 'VT': 'Vermont',
        # 'WA': 'Washington',
        # 'WI': 'Wisconsin',
        # 'WV': 'West Virginia',
        # 'WY': 'Wyoming'
}